max_configs:
    1000

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    device: ['cuda:3']
    task: ['scifar10']
    block: ['ESN']
    layers: [8]
    dmodel: [32] # 8 * 2048
    rbatch: [1024]
    last: [False]
    readout: ['ridge']
    inputscaling: [0.1, 0.3, 0.5, 0.7]
    biasscaling: [0.0, 0.2, 0.4, 0.6]
    rho: [0.9, 1.0, 1.1]
    leaky: [0.4, 0.6, 0.8, 1.0]
    transient: [ -1 ]
    regul: [ 0.8 ]
