max_configs:
    1000

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    device: ['cuda:3']
    task: ['scifar10']
    block: ['ESN']
    layers: [1]
    dmodel: [256]
    rbatch: [1024]
    last: [False]
    readout: ['ridge']
    inputscaling: [0.25, 0.5, 0.75, 1.0, 1.25]
    biasscaling: [0.0, 0.25, 0.5, 0.75, 1.0, 1.25]
    rho: [0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1]
    leaky: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
