# 1e9a6436-6b33-4931-91ef-29fd6e1e2367
# 42,False,False,cuda:3,pmnist,ESN,2,32,1024,False,ridge,0.1,0.2,1.05,0.6,-1,0.8

max_configs:
    1

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    device: ['cuda:3']
    task: ['pmnist']
    block: ['ESN']
    layers: [2]
    dmodel: [1024] # 2 * 1024
    rbatch: [256]
    last: [False]
    readout: ['ridge']
    inputscaling: [0.1]
    biasscaling: [0.2]
    rho: [1.05]
    leaky: [0.6]
    transient: [ -1 ]
    regul: [ 0.8 ]
