max_configs:
    1

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    device: ['cuda:3']
    task: ['pmnist']
    block: ['ESN']
    layers: [1]
    dmodel: [2048] # 2 * 1024
    rbatch: [256]
    last: [False]
    readout: ['ridge']
    inputscaling: [0.1]
    biasscaling: [0.0]
    rho: [1.0]
    leaky: [1.0]
    transient: [ -1 ]
    regul: [ 0.3 ]
