# fbaf5c27-5156-4583-bb5d-ff2d34e2c13d
# 42,True,False,cuda:0,pathfinder,RSSM,8,2048,32,False,ridge,64,reservoir,1.0,1.0,Vr,real+relu,real+tanh,0.0,0.0,False,0.01,0.1,0.0,0.25,0.0,1.0,0.0,1.0,-1,0.8

max_configs:
    1

hyperparameters:
    "seed": [ 42 ]
    "save": [ False ]
    "tr": [ False ]
    "device": [ "cuda:0" ]
    "task": [ "pathfinder" ]
    "block": "[RSSM" ]
    "layers": [ 8 ]
    "dmodel": [ 2048 ]
    "rbatch": [ 32 ]
    "last": [ False ]
    "readout": [ "ridge" ]
    "dstate": [ 64 ]
    "encoder": [ "reservoir" ]
    "minscaleD": [ 1.0 ]
    "maxscaleD": [ 1.0 ]
    "kernel": [ "Vr" ]
    "funfwd": [ "real+relu" ]
    "funfit": [ "real+tanh" ]
    "strong": [ 0.0 ]
    "weak": [ 0.0 ]
    "discrete": [ False ]
    "low": [ 0.01 ]
    "high": [ 0.1 ]
    "minscaleB": [ 0.0 ]
    "maxscaleB": [ 0.25 ]
    "minscaleC": [ 0.0 ]
    "maxscaleC": [ 1.0 ]
    "minscaleencoder": [ 0.0 ]
    "maxscaleencoder": [ 1.0 ]
    "transient": [ -1 ]
    "regul": [ 1.5 ]
