max_configs:
    800

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    # DEVICE
    device: ["cuda:3"]
    # TASK
    task: ["scifar10gs"]
    # ARCHITECTURE
    block: ["RSSM"]
    layers: [1]
    dmodel: [2048]
    # BLOCK
    dstate: [4096]
    rbatch: [64]
    kernel: ["Vr"]
    funfwd: ["real+relu"]
    funfit: ["real+tanh"]
    minscaleencoder: [0.0]
    maxscaleencoder: [1.0]
    discrete: [False]
    strong: [0.0]
    weak: [0.0]
    low: [0.01]
    high: [0.01]
    minscaleB: [0.0]
    maxscaleB: [0.25]
    minscaleC: [0.0]
    maxscaleC: [1.0]
    minscaleD: [0.2]
    maxscaleD: [0.2]
    # RIDGE CLASSIFIER READOUT
    readout: ["ridge"]
    last: [False]
    transient: [-1]
    regul: [0.8]
