max_configs:
    800

hyperparameters:
    seed: [42]
    save: [True]
    tr: [False]
    device: ["cuda:0"]
    task: ["imdb"]
    block: ["RSSM"]
    layers: [8]
    dmodel: [2048]
    rbatch: [8]
    dstate: [256]
    encoder: ["onehot"]
    minscaleD: [0.75]
    maxscaleD: [1.0]
    kernel: ["Vr"]
    funfwd: ["real+relu"]
    funfit: ["real+tanh"]
    strong: [-1.0]
    weak: [-0.5]
    discrete: [False]
    low: [0.0001]
    high: [0.001]
    minscaleB: [0.0]
    maxscaleB: [1.25]
    minscaleC: [0.0]
    maxscaleC: [0.5]
    minscaleencoder: [0.0]
    maxscaleencoder: [1.25]
    regul: [0.8]
    readout: [ "mlp" ]
    last: [ False ]
    transient: [ -1 ]
    batch: [ 64 ]
    mlplayers: [ 2, 4, 6 ]
    lr: [ 0.0005, 0.001, 0.005, 0.01 ]
    wd: [ 0.01, 0.05, 0.1, 0.5 ]  # try to fix it
    plateau: [ 0.2 ]
    epochs: [ 200 ]  # aumentare
    patience: [ 10 ]  # aumentare
