max_configs:
    800

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    # DEVICE
    device: ["cuda:3"]
    # TASK
    task: ["pathfinder"]
    # ARCHITECTURE
    block: ["RSSM"]
    layers: [8]
    dmodel: [512]
    # BLOCK
    dstate: [4, 16, 64, 256, 1024]
    rbatch: [128]
    kernel: ["Vr"]
    funfwd: ["real+relu"]
    funfit: ["real+tanh"]
    encoder: ["reservoir"]
    minscaleencoder: [0.0]
    maxscaleencoder: [1.0]
    discrete: [False]
    strong: [-3.0, -2.0, -1.0, 0.0]
    weak: [0.0]
    low: [0.001]
    high: [0.1]
    minscaleB: [0.0]
    maxscaleB: [0.1, 0.2, 0.5, 0.7, 1.0]
    minscaleC: [0.0]
    maxscaleC: [0.1, 0.2, 0.5, 0.7, 1.0]
    minscaleD: [0.0, 0.5, 1.0]
    maxscaleD: [0.0, 0.5, 1.0]
    # RIDGE CLASSIFIER READOUT
    readout: ["ridge"]
    last: [False]
    transient: [-1]
    regul: [0.8]
