max_configs:
    800

hyperparameters:
    "seed": [ 42 ]
    "save": [ True ]
    "tr": [ False ]
    "device": [ "cuda:1" ]
    "task": [ "pathfinder" ]
    "block": [ "RSSM" ]
    "layers": [ 8 ]
    "dmodel": [ 2048 ]
    "rbatch": [ 32 ]
    "dstate": [ 64 ]
    "encoder": [ "reservoir" ]
    "minscaleD": [ 1.0 ]
    "maxscaleD": [ 1.0 ]
    "kernel": [ "Vr" ]
    "funfwd": [ "real+relu" ]
    "funfit": [ "real+tanh" ]
    "strong": [ 0.0 ]
    "weak": [ 0.0 ]
    "discrete": [ False ]
    "low": [ 0.01 ]
    "high": [ 0.1 ]
    "minscaleB": [ 0.0 ]
    "maxscaleB": [ 0.25 ]
    "minscaleC": [ 0.0 ]
    "maxscaleC": [ 1.0 ]
    "minscaleencoder": [ 0.0 ]
    "maxscaleencoder": [ 1.0 ]
    "regul": [ 0.8 ]
    readout: [ "mlp" ]
    last: [ False ]
    transient: [ -1 ]
    batch: [ 64 ]
    mlplayers: [ 2, 4, 6 ]
    lr: [ 0.0005, 0.001, 0.005, 0.01 ]
    wd: [ 0.01, 0.05, 0.1, 0.5 ]
    plateau: [ 0.2 ]
    epochs: [ 200 ]
    patience: [ 10 ]
