# c52692d9-e3f8-4c42-965b-b05a6392619c
# 42,False,False,cuda:0,scifar10gs,RSSM,8,128,512,False,ridge,1024,reservoir,0.5,1.0,Vr,real+relu,real+tanh,-2.5,0.0,False,0.01,0.1,0.0,0.5,0.0,0.75,0.0,0.25,-1,0.8

max_configs:
    1

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    device: ["cuda:0"]
    task: ["scifar10gs"]
    block: ["RSSM"]
    layers: [8]
    dmodel: [2048]
    rbatch: [32]
    last: [False]
    readout: ["ridge"]
    dstate: [1024]
    encoder: ["reservoir"]
    minscaleD: [0.5]
    maxscaleD: [1.0]
    kernel: ["Vr"]
    funfwd: ["real+relu"]
    funfit: ["real+tanh"]
    strong: [-2.5]
    weak: [0.0]
    discrete: [False]
    low: [0.01]
    high: [0.1]
    minscaleB: [0.0]
    maxscaleB: [0.5]
    minscaleC: [0.0]
    maxscaleC: [0.75]
    minscaleencoder: [0.0]
    maxscaleencoder: [0.25]
    transient: [-1]
    regul: [12.5]
