mode:
    'classification'

architecture:
    criterion: 'cross_entropy'
    to_vec: True
    to_embed: False
    d_input: 1
    kernel_size: 784  # 28 * 28
    d_output: 10

learning:
    val_split: 0.1
    