# 4975eb56-ff48-4a3c-bc4e-ac4707311ef5
# 42,False,False,cuda:3,scifar10,ESN,8,32,1024,False,ridge,0.6,0.4,1.0,0.7,-1,0.8

max_configs:
    1

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    device: ['cuda:3']
    task: ['scifar10']
    block: ['ESN']
    layers: [8]
    dmodel: [2048] # 2 * 1024
    rbatch: [32]
    last: [False]
    readout: ['ridge']
    inputscaling: [0.6]
    biasscaling: [0.4]
    rho: [1.0]
    leaky: [0.7]
    transient: [ -1 ]
    regul: [ 0.8 ]
