# 41df02d2-9fe4-4f09-a8c5-d9c633aa7faf
# 42,False,False,cuda:3,scifar10,ESN,8,64,1024,False,ridge,1.25,0.75,1.0,0.1,-1,0.8

max_configs:
    1

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    device: ['cuda:3']
    task: ['scifar10']
    block: ['ESN']
    layers: [8]
    dmodel: [2048] # 2 * 1024
    rbatch: [32]
    last: [False]
    readout: ['ridge']
    inputscaling: [1.25]
    biasscaling: [0.75]
    rho: [1.0]
    leaky: [0.1]
    transient: [ -1 ]
    regul: [ 0.8 ]
