# e37d90eb-ab22-4c4c-9af2-3bc55c18aa15
# 1x256,42,False,False,cuda:3,scifar10,ESN,1,256,1024,False,ridge,1.0,1.25,1.0,0.1,-1,0.8

max_configs:
    1

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    device: ['cuda:3']
    task: ['scifar10']
    block: ['ESN']
    layers: [1]
    dmodel: [16384] # 8 * 2048
    rbatch: [32]
    last: [False]
    readout: ['ridge']
    inputscaling: [1.0]
    biasscaling: [1.25]
    rho: [1.0]
    leaky: [0.1]
    transient: [ -1 ]
    regul: [ 12.5 ]
