# e585e42e-c58f-4265-9aa4-50fcb88cedc8
# 42,False,False,cuda:0,scifar10,RSSM,8,128,512,False,ridge,64,reservoir,0.25,1.0,Vr,real+relu,real+tanh,0.0,0.0,False,0.0001,0.1,0.0,0.75,0.0,0.1,0.0,0.75,-1,0.8
max_configs:
    1

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    # DEVICE
    device: ["cuda:3"]
    # TASK
    task: ["scifar10"]
    # ARCHITECTURE
    block: ["RSSM"]
    layers: [8]
    dmodel: [2048]
    # BLOCK
    dstate: [64]
    rbatch: [32]
    kernel: ["Vr"]
    funfwd: ["real+relu"]
    funfit: ["real+tanh"]
    encoder: ["reservoir"]
    minscaleencoder: [0.0]
    maxscaleencoder: [0.75]
    discrete: [False]
    strong: [0.0]
    weak: [0.0]
    low: [0.0001]
    high: [0.1]
    minscaleB: [0.0]
    maxscaleB: [0.75]
    minscaleC: [0.0]
    maxscaleC: [0.1]
    minscaleD: [0.25]
    maxscaleD: [1.0]
    # RIDGE CLASSIFIER READOUT
    readout: ["ridge"]
    last: [False]
    transient: [-1]
    regul: [12.5]  # 0.8
