max_configs:
    800

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    # DEVICE
    device: ["cuda:3"]
    # TASK
    task: ["pathfinder32easy"]
    # BLOCK
    block: ["RSSM"]
    layers: [1, 2, 3, 4, 5, 6]
    neurons: [64]
    rbatch: [512]
    kernel: ["Vr"]
    funfwd: ["real+relu"]
    funfit: ["real+tanh"]
    minscaleencoder: [0.0]
    maxscaleencoder: [1.0]
    discrete: [False]
    strong: [-4.0]
    weak: [-0.025]
    low: [0.001]
    high: [0.1]
    minscaleB: [0.0]
    maxscaleB: [0.25]
    minscaleC: [0.0]
    maxscaleC: [1.0]
    minscaleD: [1.0]
    maxscaleD: [1.0]
    # RIDGE CLASSIFIER READOUT
    readout: ["ridge"]
    last: [False]
    transient: [-1]
    regul: [0.8]
