max_configs:
    1

hyperparameters:
    seed: [ 42 ]
    save: [ False ]
    tr: [ False ]
    device: [ "cuda:3" ]
    task: [ "smnist" ]
    block: [ "RSSM" ]
    layers: [ 2 ]
    dmodel: [ 1024 ]
    rbatch: [ 256 ]
    dstate: [ 512 ]
    encoder: [ "reservoir" ]
    minscaleD: [ 0.25 ]
    maxscaleD: [ 0.75 ]
    kernel: [ "Vr" ]
    funfwd: [ "real+relu" ]
    funfit: [ "real+tanh" ]
    strong: [ -3.5 ]
    weak: [ 0.0 ]
    discrete: [ False ]
    low: [ 0.0001 ]
    high: [ 0.1 ]
    minscaleB: [ 0.0 ]
    maxscaleB: [ 1.25 ]
    minscaleC: [ 0.0 ]
    maxscaleC: [ 1.0 ]
    minscaleencoder: [ 0.0 ]
    maxscaleencoder: [ 0.25 ]
    # MLP READOUT
    readout: ["mlp"]
    last: [False]
    transient: [-1]
    batch: [128]
    mlplayers: [2]
    lr: [0.005]
    wd: [0.1]
    plateau: [0.2]
    epochs: [200] # 26
    patience: [10]
