max_configs:
    1

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    # DEVICE
    device: ["cuda:1"]
    # TASK
    task: ["listops"]
    # ARCHITECTURE
    block: ["LRSSM"]
    layers: [8]
    dmodel: [64]
    # BLOCK
    dstate: [512]
    kernel: ["Vr"]
    minscaleencoder: [0.0]
    maxscaleencoder: [0.25]
    discrete: [False]
    strong: [-0.5]
    weak: [-0.5]
    low: [0.001]
    high: [0.01]
    minscaleB: [0.0]
    maxscaleB: [1.0]
    minscaleC: [0.0]
    maxscaleC: [1.0]
    minscaleD: [0.0]
    maxscaleD: [0.25]
    # LEARNING
    batch: [64]
    mlplayers: [1]
    act: ["glu"]
    encoder: ["embedding"]
    decoder: ["conv1d"]
    dropout: [0.0]
    layerdrop: [0.0]
    lr: [0.005]
    wd: [0.01]
    plateau: [0.2]
    epochs: [200]
    patience: [10]
