max_configs:
    800

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    # DEVICE
    device: ["cuda:1"]
    # TASK
    task: ["listops"]
    # ARCHITECTURE
    block: ["RSSM"]
    layers: [8]
    dmodel: [128]
    # BLOCK
    dstate: [1024]
    rbatch: [64]
    kernel: ["Vr"]
    funfwd: ["real+relu"]
    funfit: ["real+tanh"]
    encoder: ["onehot"]
    minscaleencoder: [0.0]
    maxscaleencoder: [1.25]
    discrete: [False]
    strong: [-2.5]
    weak: [0.0]
    low: [0.001]
    high: [0.1]
    minscaleB: [0.0]
    maxscaleB: [0.1]
    minscaleC: [0.0]
    maxscaleC: [1.25]
    minscaleD: [1.0]
    maxscaleD: [1.0]
    # RIDGE CLASSIFIER READOUT
    readout: ["ridge"]
    last: [False]
    transient: [-1]
    regul: [0.8]
